In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x=tf.constant(4)
x=tf.constant([[1,3,2],[4,5,6]],dtype=tf.float32)
x=tf.zeros((2,3))
x=tf.ones((3,4),dtype=tf.float32)
x=tf.eye(3)#for the identity matrix, the one will be on the diagonal
x=tf.random.normal((3,3),mean=0,stddev=1)
x=tf.range(9)
# changing the datatype
x=tf.cast(x,dtype=tf.int32)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [3]:
# mathematical operations
a=tf.constant([7,8,9])
b=tf.constant([10,11,12])
c=tf.add(a,b)
print(c)

tf.Tensor([17 19 21], shape=(3,), dtype=int32)


In [4]:
# subtraction
z=a-b
# dot products
dot_Prod=tf.tensordot(a,b,axes=1)
print(dot_Prod)

tf.Tensor(266, shape=(), dtype=int32)


In [5]:
d=tf.reduce_sum(a*b,axis=0)
d
# expo
print(a**5)

tf.Tensor([16807 32768 59049], shape=(3,), dtype=int32)


In [6]:
# matrix multiplication
a=tf.random.normal((2,3))
b=tf.random.normal((3,4))
print(tf.tensordot(a,b,axes=1))
print(tf.matmul(a,b))
print(a@b)


tf.Tensor(
[[ 0.57942176 -2.0628393  -1.7976931   1.285566  ]
 [ 0.25235772 -0.5032986  -0.5697101   0.4625857 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.57942176 -2.0628393  -1.7976931   1.285566  ]
 [ 0.25235772 -0.5032986  -0.5697101   0.4625857 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.57942176 -2.0628393  -1.7976931   1.285566  ]
 [ 0.25235772 -0.5032986  -0.5697101   0.4625857 ]], shape=(2, 4), dtype=float32)


In [7]:
# tensor indexing
x=tf.constant([0,1,2,3,43,223,122,1,5,56,32])
print(x[:])
print(x[1:])
print(x[2:-1])

tf.Tensor([  0   1   2   3  43 223 122   1   5  56  32], shape=(11,), dtype=int32)
tf.Tensor([  1   2   3  43 223 122   1   5  56  32], shape=(10,), dtype=int32)
tf.Tensor([  2   3  43 223 122   1   5  56], shape=(8,), dtype=int32)


In [8]:
# reshape
r=tf.range(9)
r=tf.reshape(r,(3,3))
r

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [9]:
# swap rows for columns
r=tf.transpose(r,perm=[1,0])
r

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>

### TENSORFLOW CLASSIFICATION
#### Sequential API

In [10]:
import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras.datasets import mnist

In [11]:
# loading our dataset
(x_train,y_train),(x_test,y_test)=mnist.load_data()
# visualize the data
x_train.shape
x_test.shape

(10000, 28, 28)

In [12]:
# lets reshape the data
x_train=x_train.reshape(-1,28*28).astype("float32")/255 #we divide by 255 to normalize the data
x_test=x_train.reshape(-1,28*28).astype("float32")/255

In [13]:
# we use the Sequential API when the output and input is one
# it is very convenient but not very flexible
model=keras.Sequential([
    layers.Dense(512,activation="relu",input_shape=[28*28]),
    layers.Dense(256,activation="relu"),
    layers.Dense(10),
 ])

# the compile method specifies what optimizers and what network configurations
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)
# now lets train
model.fit(
    x_train,
    y_train,
    batch_size=52,
    epoch=5,
    verbose=2
)
model.evaluate(
    x_test,
    y_test,
    epoch=5,
    batch_size=32,
)


Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\Martin\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Martin\AppData\Local\Temp\ipykernel_4432\1211713649.py", line 16, in <module>
    model.fit(
  File "c:\Users\Martin\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\Users\Martin\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    filtered_tb = _process_traceback_frames(e.__traceback__)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Model.fit() got an unexpected keyword argument 'epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Martin\AppData\Loca

In [14]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


#### Functional API

In [15]:
inputs=keras.Input(shape=(784))

In [16]:
x=layers.Dense(512,activation="relu")(inputs)
x=layers.Dense(256,activation="relu")(x)
outputs=layers.Dense(10,activation="softmax")(x)

# model definition
model=keras.Model(inputs=inputs,outputs=outputs)

In [17]:
# compile the model
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

In [18]:
model.fit(
    x_train,
    y_train,
    verbose=2,
    batch_size=52,
    epochs=5
)
model.evaluate(
    x_test,
    y_test,
    batch_size=32,
)

Epoch 1/5
1154/1154 - 33s - loss: 0.1919 - accuracy: 0.9422 - 33s/epoch - 29ms/step
Epoch 2/5
1154/1154 - 44s - loss: 0.0786 - accuracy: 0.9752 - 44s/epoch - 38ms/step
Epoch 3/5
1154/1154 - 43s - loss: 0.0526 - accuracy: 0.9829 - 43s/epoch - 38ms/step
Epoch 4/5
1154/1154 - 48s - loss: 0.0380 - accuracy: 0.9880 - 48s/epoch - 42ms/step
Epoch 5/5
1154/1154 - 39s - loss: 0.0315 - accuracy: 0.9893 - 39s/epoch - 33ms/step


ValueError: Data cardinality is ambiguous:
  x sizes: 60000
  y sizes: 10000
Make sure all arrays contain the same number of samples.

In [ ]:
model=keras.Model(inputs=model.inputs,outputs=[model.layers[-1].output])
features=model.predict(x_test)
print(features)


In [ ]:
model=keras.Model(inputs=model.inputs)